language: node_js
node_js: node
branches:
  only:
  - master
script:
  - npm run build
  - npm run test
  - npm run build:doc
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/doc
  on:
    tags: true